@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Riad Younes",
  "email": "riad.younes2@gmail.com",
  "password": "123546"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "riad.younes2@gmail.com",
  "password": "123546"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Create a new question 31",
  "content": "create new content question"
}


###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=2
Content-Type: application/json
Authorization: Bearer {{authToken}}




